import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, Bricolage_Grotesque } from "next/font/google";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import PageHeader from "@/components/PageHeader";

export const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
  fallback: ["system-ui", "arial"],
});

export const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Weather Now",
  description: "Generated by FrontEnd Mentor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased text-400 font-medium leading-[1.2] bg-neutral-900 px-4 pt-4 pb-12 md:px-6 md:pt-6 md:pb-20 lg:px-12 lg:pt-12 text-neutral-0`}
      >
        <MaxWidthWrapper className="grid gap-12 lg:gap-16">
          <PageHeader />
          {children}
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
